// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type NoticiaprincipalDocumentDataSlicesSlice = never;

/**
 * Content for noticiaprincipal documents
 */
interface NoticiaprincipalDocumentData {
  /**
   * titulonoticia field in *noticiaprincipal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: noticiaprincipal.titulonoticia
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulonoticia: prismic.KeyTextField;

  /**
   * subtitulonoticia field in *noticiaprincipal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: noticiaprincipal.subtitulonoticia
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitulonoticia: prismic.KeyTextField;

  /**
   * imagemnoticia field in *noticiaprincipal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: noticiaprincipal.imagemnoticia
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagemnoticia: prismic.ImageField<never>;

  /**
   * artigonoticia field in *noticiaprincipal*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: noticiaprincipal.artigonoticia
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  artigonoticia: prismic.RichTextField;

  /**
   * datanoticia field in *noticiaprincipal*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: noticiaprincipal.datanoticia
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  datanoticia: prismic.DateField;

  /**
   * autornoticia field in *noticiaprincipal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: noticiaprincipal.autornoticia
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  autornoticia: prismic.KeyTextField;

  /**
   * fotoautor field in *noticiaprincipal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: noticiaprincipal.fotoautor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fotoautor: prismic.ImageField<never>;

  /**
   * Slice Zone field in *noticiaprincipal*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: noticiaprincipal.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<NoticiaprincipalDocumentDataSlicesSlice> /**
   * Meta Description field in *noticiaprincipal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: noticiaprincipal.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *noticiaprincipal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: noticiaprincipal.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *noticiaprincipal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: noticiaprincipal.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * noticiaprincipal document from Prismic
 *
 * - **API ID**: `noticiaprincipal`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NoticiaprincipalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NoticiaprincipalDocumentData>,
    "noticiaprincipal",
    Lang
  >;

export type AllDocumentTypes = NoticiaprincipalDocument;

/**
 * Default variation for NoticiaPrinciapl Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NoticiaPrinciaplSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *NoticiaPrinciapl*
 */
type NoticiaPrinciaplSliceVariation = NoticiaPrinciaplSliceDefault;

/**
 * NoticiaPrinciapl Shared Slice
 *
 * - **API ID**: `noticia_princiapl`
 * - **Description**: NoticiaPrinciapl
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NoticiaPrinciaplSlice = prismic.SharedSlice<
  "noticia_princiapl",
  NoticiaPrinciaplSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      NoticiaprincipalDocument,
      NoticiaprincipalDocumentData,
      NoticiaprincipalDocumentDataSlicesSlice,
      AllDocumentTypes,
      NoticiaPrinciaplSlice,
      NoticiaPrinciaplSliceVariation,
      NoticiaPrinciaplSliceDefault,
    };
  }
}
