// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Post documents
 */
interface PostmeDocumentData {
  /**
   * title post field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Postme.title_post
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_post: prismic.KeyTextField;

  /**
   * title presentation content field in *Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Postme.title_presentation_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title_presentation_content: prismic.KeyTextField;

  /**
   * text presentation content field in *Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Postme.text_presentation_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text_presentation_content: prismic.RichTextField;

  /**
   * image presentation content field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: Postme.image_presentation_content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_presentation_content: prismic.ImageField<never>;

  /**
   * high content post  field in *Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Postme.high_content_post
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  high_content_post: prismic.RichTextField;

  /**
   * left image post field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: Postme.left_image_post
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  left_image_post: prismic.ImageField<never>;

  /**
   * right image post field in *Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: Postme.right_image_post
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  right_image_post: prismic.ImageField<never>;

  /**
   * low content post  field in *Post*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: Postme.low_content_post
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  low_content_post: prismic.RichTextField;
}

/**
 * Post document from Prismic
 *
 * - **API ID**: `Postme`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostmeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PostmeDocumentData>, "Postme", Lang>;

type PagepostDocumentDataSlicesSlice = never;

/**
 * Content for PagePost documents
 */
interface PagepostDocumentData {
  /**
   * Slice Zone field in *PagePost*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: pagepost.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PagepostDocumentDataSlicesSlice> /**
   * Meta Description field in *PagePost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: pagepost.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *PagePost*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pagepost.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *PagePost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: pagepost.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * PagePost document from Prismic
 *
 * - **API ID**: `pagepost`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PagepostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PagepostDocumentData>,
    "pagepost",
    Lang
  >;

export type AllDocumentTypes = PostmeDocument | PagepostDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PostmeDocument,
      PostmeDocumentData,
      PagepostDocument,
      PagepostDocumentData,
      PagepostDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
