version: '4.3'
services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senhaquantumchique
      - POSTGRES_DB=lapadarie_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: api-container
    environment:
      - DATABASE_URL=postgresql://postgres:senhaquantumchique@postgres:5432/lapadarie_db
      - PORT=3000
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - .:/app

volumes:
  postgres-data:
