services:
  node:
    image: node:16-alpine
    container_name: node
    # Keeps container running
    tty: true
    # Allows to read from stdin
    stdin_open: true
    command: sh
    # Restarts the container unless stopped
    restart: unless-stopped
    # Exposes default Node.js port
    ports:
      - "3001:3000"
    volumes:
      - ./:/app
    working_dir: /app
    # Configuration and sensitive data
    env_file: .env
    # Environment variables
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      # Checks if port 3000 is being used
      test: ["CMD", "lsof", "-t", "-i:3001"]
      timeout: 10s
      retries: 5
  db:
    image: mysql:8.0.32
    container_name: db
    restart: unless-stopped
    # Exposes default MySQL port
    ports:
      - "3307:3306"
    # Configuration and sensitive data
    env_file: .env
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    # Applies initial migration on build
    volumes:
      - ./prisma/migrations/migration.sql:/docker-entrypoint-initdb.d/migration.sql
    healthcheck:
      # Pings MySQL server
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5