// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AutorDocumentDataSlicesSlice = IconePostSlice;

/**
 * Content for Autor documents
 */
interface AutorDocumentData {
  /**
   * Nome field in *Autor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: autor.nome
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome: prismic.KeyTextField;

  /**
   * Icone field in *Autor*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: autor.icone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icone: prismic.ImageField<never>;

  /**
   * Texto1 field in *Autor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: autor.texto1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texto1: prismic.KeyTextField;

  /**
   * Instagram field in *Autor*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: autor.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField;

  /**
   * Linkedin field in *Autor*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: autor.linkedin
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin: prismic.LinkField;

  /**
   * Github field in *Autor*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: autor.github
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  github: prismic.LinkField;

  /**
   * Texto2 field in *Autor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: autor.texto2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texto2: prismic.KeyTextField;

  /**
   * Mais do Autor field in *Autor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: autor.mais_do_autor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mais_do_autor: prismic.KeyTextField;

  /**
   * Slice Zone field in *Autor*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: autor.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AutorDocumentDataSlicesSlice>;
}

/**
 * Autor document from Prismic
 *
 * - **API ID**: `autor`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AutorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AutorDocumentData>, "autor", Lang>;

/**
 * Item in *Cabeçalho → Conteudo*
 */
export interface CabecalhoDocumentDataConteudoItem {
  /**
   * Link Logo field in *Cabeçalho → Conteudo*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cabecalho.conteudo[].link_logo
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_logo: prismic.LinkField;

  /**
   * caixa pesquisa field in *Cabeçalho → Conteudo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cabecalho.conteudo[].caixa_pesquisa
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  caixa_pesquisa: prismic.KeyTextField;
}

/**
 * Content for Cabeçalho documents
 */
interface CabecalhoDocumentData {
  /**
   * Conteudo field in *Cabeçalho*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: cabecalho.conteudo[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  conteudo: prismic.GroupField<Simplify<CabecalhoDocumentDataConteudoItem>>;
}

/**
 * Cabeçalho document from Prismic
 *
 * - **API ID**: `cabecalho`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CabecalhoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CabecalhoDocumentData>,
    "cabecalho",
    Lang
  >;

type HomepageDocumentDataSlicesSlice = IconePostSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Titulo field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * texto1 field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.texto1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto1: prismic.RichTextField;

  /**
   * Imagem field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.imagem
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem: prismic.ImageField<never>;

  /**
   * Ultimas Postagens field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.ultimas_postagens
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ultimas_postagens: prismic.KeyTextField;

  /**
   * Mais Acessadas field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.mais_acessadas
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  mais_acessadas: prismic.KeyTextField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for icone dum Post documents
 */
interface IconeDumPostDocumentData {
  /**
   * Thumbnail field in *icone dum Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: icone_dum_post.thumbnail
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * Titulo field in *icone dum Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icone_dum_post.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Descricao field in *icone dum Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icone_dum_post.descricao
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao: prismic.KeyTextField;

  /**
   * icone autor field in *icone dum Post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: icone_dum_post.icone_autor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icone_autor: prismic.ImageField<never>;

  /**
   * nome autor field in *icone dum Post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icone_dum_post.nome_autor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_autor: prismic.KeyTextField;

  /**
   * data field in *icone dum Post*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: icone_dum_post.data
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  data: prismic.DateField;
}

/**
 * icone dum Post document from Prismic
 *
 * - **API ID**: `icone_dum_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IconeDumPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<IconeDumPostDocumentData>,
    "icone_dum_post",
    Lang
  >;

type PageDocumentDataSlicesSlice = never;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type PostagemDocumentDataSlicesSlice = IconePostSlice;

/**
 * Content for postagem documents
 */
interface PostagemDocumentData {
  /**
   * titulo field in *postagem*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: postagem.titulo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * texto1 field in *postagem*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: postagem.texto1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto1: prismic.RichTextField;

  /**
   * imagem1 field in *postagem*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: postagem.imagem1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem1: prismic.ImageField<never>;

  /**
   * texto2 field in *postagem*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: postagem.texto2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto2: prismic.RichTextField;

  /**
   * imagem2 field in *postagem*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: postagem.imagem2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem2: prismic.ImageField<never>;

  /**
   * imagem3 field in *postagem*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: postagem.imagem3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem3: prismic.ImageField<never>;

  /**
   * texto3 field in *postagem*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: postagem.texto3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto3: prismic.RichTextField;

  /**
   * Slice Zone field in *postagem*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: postagem.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PostagemDocumentDataSlicesSlice>;
}

/**
 * postagem document from Prismic
 *
 * - **API ID**: `postagem`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostagemDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PostagemDocumentData>,
    "postagem",
    Lang
  >;

/**
 * Item in *Rodapé → Conteudo*
 */
export interface RodapeDocumentDataConteudoItem {
  /**
   * Conheça field in *Rodapé → Conteudo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rodape.conteudo[].conheca
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  conheca: prismic.KeyTextField;

  /**
   * Instagram field in *Rodapé → Conteudo*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: rodape.conteudo[].instagram
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField;

  /**
   * Linkedin field in *Rodapé → Conteudo*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: rodape.conteudo[].linkedin
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin: prismic.LinkField;

  /**
   * Copyright field in *Rodapé → Conteudo*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rodape.conteudo[].copyright
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright: prismic.KeyTextField;
}

/**
 * Content for Rodapé documents
 */
interface RodapeDocumentData {
  /**
   * Conteudo field in *Rodapé*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: rodape.conteudo[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  conteudo: prismic.GroupField<Simplify<RodapeDocumentDataConteudoItem>>;
}

/**
 * Rodapé document from Prismic
 *
 * - **API ID**: `rodape`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RodapeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<RodapeDocumentData>,
    "rodape",
    Lang
  >;

export type AllDocumentTypes =
  | AutorDocument
  | CabecalhoDocument
  | HomepageDocument
  | IconeDumPostDocument
  | PageDocument
  | PostagemDocument
  | RodapeDocument;

/**
 * Item in *IconePost → Default → Primary → Autor*
 */
export interface IconePostSliceDefaultPrimaryAutorItem {
  /**
   * icone field in *IconePost → Default → Primary → Autor*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: icone_post.default.primary.autor[].icone
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icone: prismic.ImageField<never>;

  /**
   * Nome field in *IconePost → Default → Primary → Autor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icone_post.default.primary.autor[].nome
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome: prismic.KeyTextField;

  /**
   * data field in *IconePost → Default → Primary → Autor*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icone_post.default.primary.autor[].data
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  data: prismic.KeyTextField;
}

/**
 * Primary content in *IconePost → Default → Primary*
 */
export interface IconePostSliceDefaultPrimary {
  /**
   * Titulo field in *IconePost → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icone_post.default.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Descricao field in *IconePost → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icone_post.default.primary.descricao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao: prismic.KeyTextField;

  /**
   * Thumbnail field in *IconePost → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: icone_post.default.primary.thumbnail
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;

  /**
   * Autor field in *IconePost → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: icone_post.default.primary.autor[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  autor: prismic.GroupField<Simplify<IconePostSliceDefaultPrimaryAutorItem>>;
}

/**
 * Default variation for IconePost Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconePostSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IconePostSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *IconePost → Display diferente → Primary*
 */
export interface IconePostSliceDisplayDiferentePrimary {
  /**
   * Titulo field in *IconePost → Display diferente → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icone_post.displayDiferente.primary.titulo
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  titulo: prismic.KeyTextField;

  /**
   * Descricao field in *IconePost → Display diferente → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: icone_post.displayDiferente.primary.descricao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descricao: prismic.KeyTextField;

  /**
   * Autor field in *IconePost → Display diferente → Primary*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: icone_post.displayDiferente.primary.autor
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  autor: prismic.ContentRelationshipField;

  /**
   * Botao Compartilhar field in *IconePost → Display diferente → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: icone_post.displayDiferente.primary.botao_compartilhar
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  botao_compartilhar: prismic.ImageField<never>;

  /**
   * Thumbnail field in *IconePost → Display diferente → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: icone_post.displayDiferente.primary.thumbnail
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  thumbnail: prismic.ImageField<never>;
}

/**
 * Display diferente variation for IconePost Slice
 *
 * - **API ID**: `displayDiferente`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconePostSliceDisplayDiferente = prismic.SharedSliceVariation<
  "displayDiferente",
  Simplify<IconePostSliceDisplayDiferentePrimary>,
  never
>;

/**
 * Slice variation for *IconePost*
 */
type IconePostSliceVariation =
  | IconePostSliceDefault
  | IconePostSliceDisplayDiferente;

/**
 * IconePost Shared Slice
 *
 * - **API ID**: `icone_post`
 * - **Description**: IconePost
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconePostSlice = prismic.SharedSlice<
  "icone_post",
  IconePostSliceVariation
>;

/**
 * Primary content in *WidgetAutor → Default → Primary*
 */
export interface WidgetAutorSliceDefaultPrimary {
  /**
   * Icone field in *WidgetAutor → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: widget_autor.default.primary.icone
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  icone: prismic.ImageField<never>;

  /**
   * Nome field in *WidgetAutor → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: widget_autor.default.primary.nome
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome: prismic.KeyTextField;

  /**
   * Data field in *WidgetAutor → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: widget_autor.default.primary.data
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  data: prismic.DateField;
}

/**
 * Default variation for WidgetAutor Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WidgetAutorSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WidgetAutorSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WidgetAutor*
 */
type WidgetAutorSliceVariation = WidgetAutorSliceDefault;

/**
 * WidgetAutor Shared Slice
 *
 * - **API ID**: `widget_autor`
 * - **Description**: WidgetAutor
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WidgetAutorSlice = prismic.SharedSlice<
  "widget_autor",
  WidgetAutorSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AutorDocument,
      AutorDocumentData,
      AutorDocumentDataSlicesSlice,
      CabecalhoDocument,
      CabecalhoDocumentData,
      CabecalhoDocumentDataConteudoItem,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      IconeDumPostDocument,
      IconeDumPostDocumentData,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      PostagemDocument,
      PostagemDocumentData,
      PostagemDocumentDataSlicesSlice,
      RodapeDocument,
      RodapeDocumentData,
      RodapeDocumentDataConteudoItem,
      AllDocumentTypes,
      IconePostSlice,
      IconePostSliceDefaultPrimaryAutorItem,
      IconePostSliceDefaultPrimary,
      IconePostSliceDisplayDiferentePrimary,
      IconePostSliceVariation,
      IconePostSliceDefault,
      IconePostSliceDisplayDiferente,
      WidgetAutorSlice,
      WidgetAutorSliceDefaultPrimary,
      WidgetAutorSliceVariation,
      WidgetAutorSliceDefault,
    };
  }
}
