// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  author_card: dynamic(() => import("./AuthorCard")),
  featured_post: dynamic(() => import("./FeaturedPost")),
};
