// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  featured_post: dynamic(() => import("./FeaturedPost")),
  rich_text: dynamic(() => import("./RichText")),
};
