import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/styles/global.css"
import "@/app/styles/home.css"
import "@/app/styles/reset.css"
import "@/app/styles/logo.css"
import "@/app/styles/register.css"
import "@/app/styles/login.css"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
