// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  header: dynamic(() => import("./Header")),
  post_card: dynamic(() => import("./PostGrid")),
};
