// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cabecalho: dynamic(() => import("./Cabecalho")),
  rodape: dynamic(() => import("./Rodape")),
};
