// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  icone_post: dynamic(() => import("./IconePost")),
  widget_autor: dynamic(() => import("./WidgetAutor")),
};
