import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../Components/(Header)/Page";
import Footer from "@/Components/(Footer)/Page";
import ThemeProviderFunction from "@/Components/Providers/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProviderFunction
        attribute="class"
        defaultTheme="system"
        enableSystem>
            <Header/>
            {children}
            <Footer/>
        </ThemeProviderFunction>
      </body>
    </html>
  );
}
