// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type HomepageDocumentDataSlicesSlice = FeaturedPostSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Main section header field in *Homepage*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Main section header
   * - **API ID Path**: homepage.main_section_header
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  main_section_header: prismic.TitleField;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Settings → Social networks*
 */
export interface LogoDocumentDataSocialNetworksItem {
  /**
   * URL to network field in *Settings → Social networks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.social_networks[].url_to_network
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url_to_network: prismic.LinkField;

  /**
   * Social media icon field in *Settings → Social networks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.social_networks[].social_media_icon
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  social_media_icon: prismic.ImageField<never>;
}

/**
 * Content for Settings documents
 */
interface LogoDocumentData {
  /**
   * Social networks field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.social_networks[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_networks: prismic.GroupField<
    Simplify<LogoDocumentDataSocialNetworksItem>
  >;

  /**
   * Meta description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Call to networks field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.call_to_networks
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  call_to_networks: prismic.KeyTextField;

  /**
   * Copywright info field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.copywright_info
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copywright_info: prismic.KeyTextField;

  /**
   * Theme toggle field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.theme_toggle
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  theme_toggle: prismic.ImageField<"mobile" | "desktop">;

  /**
   * Site title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Blog image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.blog_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  blog_image: prismic.ImageField<"desktop" | "mobile">;

  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logo.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<"mobile">;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `logo`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LogoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<LogoDocumentData>, "logo", Lang>;

export type AllDocumentTypes = HomepageDocument | LogoDocument;

/**
 * Primary content in *FeaturedPost → Default → Primary*
 */
export interface FeaturedPostSliceDefaultPrimary {
  /**
   * postTitle field in *FeaturedPost → Default → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_post.default.primary.posttitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  posttitle: prismic.TitleField;

  /**
   * postDescription field in *FeaturedPost → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_post.default.primary.postdescription
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  postdescription: prismic.RichTextField;

  /**
   * postImage field in *FeaturedPost → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_post.default.primary.postimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  postimage: prismic.ImageField<"mobile" | "desktop">;
}

/**
 * Default variation for FeaturedPost Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedPostSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedPostSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedPost*
 */
type FeaturedPostSliceVariation = FeaturedPostSliceDefault;

/**
 * FeaturedPost Shared Slice
 *
 * - **API ID**: `featured_post`
 * - **Description**: FeaturedPost
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedPostSlice = prismic.SharedSlice<
  "featured_post",
  FeaturedPostSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      LogoDocument,
      LogoDocumentData,
      LogoDocumentDataSocialNetworksItem,
      AllDocumentTypes,
      FeaturedPostSlice,
      FeaturedPostSliceDefaultPrimary,
      FeaturedPostSliceVariation,
      FeaturedPostSliceDefault,
    };
  }
}
