// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * aitoday field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.aitoday
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  aitoday: prismic.ImageField<never>;

  /**
   * cosmonauta field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.cosmonauta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cosmonauta: prismic.ImageField<never>;

  /**
   * textPostImg field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.textpostimg
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textpostimg: prismic.KeyTextField;

  /**
   * titulosecundario field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.titulosecundario
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulosecundario: prismic.RichTextField;

  /**
   * tituloMaisAcessadas field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.titulomaisacessadas
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulomaisacessadas: prismic.RichTextField;

  /**
   * tituloHomePrincipal field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.titulohomeprincipal
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulohomeprincipal: prismic.RichTextField;

  /**
   * titulotextinghome field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.titulotextinghome
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  titulotextinghome: prismic.RichTextField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

export type AllDocumentTypes = HomeDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type { HomeDocument, HomeDocumentData, AllDocumentTypes };
  }
}
